language: node_js
node_js:
  - "8"

install:
  - "npm install --save highcharts"
  - "npm install --save @firebase/app @firebase/firestore highcharts-vue vue-firestore"

script:
  - "npm run build"

before_deploy:
- cd ${root}


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local_dir: dist
  on:
    branch: master

notifications:
  slack: briskless:6SROHyaJqB8JAPV28vlAUyRX